name: Build ESP32

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: List build outputs
        run: ls -R .pio/build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32-c3-devkitm-1/firmware.bin
